---
version: '3'

tasks:
  hoy-chains-seal-ssh:
    desc: create and seal the ssh deploy key for the hoy-chains tenant repository
    cmds:
      - |
        set -e
        NAME=hoy-chains
        tusk -qf tusk.yml \
          git-deploykey \
          --namespace flux-system \
          --name $NAME \
          tenants/hoy-chains/tmp
        mv tenants/$NAME/tmp/secret-${NAME}sealed.yaml tenants/$NAME/
        cat tenants/$NAME/tmp/identity.pub
        echo "NOW GO UPDATE THE DEPLOY KEY for polysensus/$NAME to the above public key"
        grep "  - secret-${NAME}sealed.yaml" tenants/$NAME/kustomization.yaml && exit 0
        echo "  - secret-${NAME}sealed.yaml" >> tenants/$NAME/kustomization.yaml
        echo "Added secret-${NAME}sealed.yaml to tenants/$NAME/kustomization.yaml"

  update-secrets:
    desc: update all the sealed secrets
    cmds:
      - task: hoy-chains-seal-ssh

