# The fleet repository can constrain the target repository to ONLY create
# resources in the fleet repository defined namespace. This is achieved by
# setting the serviceAccountName on the fluxcd Kustomisation and creating that
# service account in the dictated namespace
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    toolkit.fluxcd.io/tenant: chaintrap
  name: chaintrap
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    toolkit.fluxcd.io/tenant: chaintrap
  name: chaintrap-reconciler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: gotk:chaintrap:reconciler
- kind: ServiceAccount
  name: chaintrap
