apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tenant-chaintrap
  namespace: flux-system
spec:
  interval: 20s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./tenants/chaintrap
  prune: true
