apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: hoy-chains
  namespace: flux-system
spec:
  interval: 20s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./tenants/hoy-chains
  prune: true
