# The fleet repository can constrain the target repository to ONLY create
# resources in the fleet repository defined namespace. This is achieved by
# setting the serviceAccountName on the fluxcd Kustomisation and creating that
# service account in the dictated namespace
#
# The fleet repository may create multiple namespaces per project, all it needs
# to do is refer to a base with the roles & service accounts and target it at
# each namespace with appropriate patches. The sources do not need to be
# re-written

---
# A source reference that pulls the tenant flux configuration from a seperate
# repository
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: fluxcd-<namespace>
spec:
  interval: 30s
  ref:
    branch: main
  url: ssh://git@github.com/polysensus/fluxcd-<namespace>.git
  secretRef:
    name: fluxcd-<namespace>

---
# flux kustomization of the git source reference. It specifies the path in
# which the k8s/kustomize resource is found in the target repository. Note the
# kind is the same as the k8s Kustomization but its not the same thing at all.
# flux/Kustomization's apply flux specific behaviour to flux specific resources
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: fluxcd-<namespace>
spec:
  interval: 30s
  path: ./
  prune: true
  # DONT allow the repository to create namespaces by running an explicit serviceAccount
  serviceAccountName: fluxcd-<namespace>
  sourceRef:
    kind: GitRepository
    name: fluxcd-<namespace>
