apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tenant-chaintrap
  namespace: flux-system
spec:
  dependsOn:
    - name: sealed-secrets
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  serviceAccountName: kustomize-controller
  path: ./tenants/hoy/chaintrap
  prune: true
